-- 0023 — broker referral program ("Give $50, get $50"). Idempotent.

-- Short, unique, human-shareable referral code per company. Generated by default
-- so every new org gets one; existing orgs backfilled below.
create or replace function public.gen_referral_code()
returns text language sql volatile as $$
  select upper(substring(replace(gen_random_uuid()::text, '-', ''), 1, 7));
$$;

alter table public.organizations add column if not exists referral_code text;
update public.organizations set referral_code = public.gen_referral_code() where referral_code is null;
create unique index if not exists organizations_referral_code_key on public.organizations(referral_code);
alter table public.organizations alter column referral_code set default public.gen_referral_code();

-- Which org referred this one (set once at onboarding from the ?ref code).
alter table public.organizations add column if not exists referred_by_org uuid references public.organizations(id);

-- One row per (referrer → referee) relationship; drives the dashboard + the
-- $50/$50 credit state machine. referee_org is unique (a company can only be
-- referred once). Reward lifecycle:
--   referee_credited      → $50 applied to the referee's first invoice (at checkout)
--   referrer_reward_earned→ referee made a real (non-$0) payment (anti-abuse gate)
--   referrer_credited     → $50 actually applied to the referrer's Stripe balance
create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_org uuid not null references public.organizations(id) on delete cascade,
  referee_org  uuid not null unique references public.organizations(id) on delete cascade,
  code text not null,
  referee_credited boolean not null default false,
  referrer_reward_earned boolean not null default false,
  referrer_credited boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists referrals_referrer_idx on public.referrals(referrer_org);

alter table public.referrals enable row level security;
-- A company can see referrals where it is either side (for its dashboard). All
-- writes go through the service role (checkout / webhook / onboard), never clients.
drop policy if exists referrals_read on public.referrals;
create policy referrals_read on public.referrals
  for select using (
    referrer_org in (select public.my_org_ids()) or referee_org in (select public.my_org_ids())
  );
revoke insert, update, delete on public.referrals from anon, authenticated;
